[package]
name = "rtop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.20"
libc = "0.2.132"
procfs = "0.14.1"
sysinfo = "0.26.2"
tui = "0.19.0"
crossterm = "0.19"
log = "0.4"
